---
title: "brm confusion"
output: github_document
---

``` {r setup}

suppressPackageStartupMessages(library(dplyr))

library(ggplot2)
library(dplyr)

source('./code/likelihood-ugly.R')   

  # grab data, 372 observations
  # "week", "transect", "time", "cluster", "totalSpiders"
  # 
  # (this dataframe was generated by the likelihood-ugly.R function generateLikelihoodV2() )
  #

source.url <- c("https://raw.githubusercontent.com/cordphelps/brm/master/data/clusterData.csv")
clusterData.df <- read.csv(source.url, header=TRUE, row.names=NULL)

```



### How plausible is it that an oakMargin transect row will have more spiders than a control transect row?

``` {r graphics}



#   plot likelihood for all observations (24 hours), for daylight observations (collected in the 'pm'), and 
#   for nighttime observations (collected in the 'am')
#

    gg.likelihood <- generateLikelihoodV2(df=clusterData.df, daytime='24h')
    print(gg.likelihood)
  
    filtered.df <- clusterData.df %>% dplyr::filter(time == 'pm')
    gg.likelihood <- generateLikelihoodV2(df=filtered.df, daytime='pm')
    print(gg.likelihood) 
  
    filtered.df <- clusterData.df %>% dplyr::filter(time == 'am')
    gg.likelihood <- generateLikelihoodV2(df=filtered.df, daytime='am')
    print(gg.likelihood) 
  
```
