
generateLikelihoodV2 <- function(df, list, daytime) {

  
    if("rethinking" %in% (.packages())){
     detach("package:rethinking", unload=TRUE) 
    }
  
    # https://bookdown.org/connect/#/apps/1850/access
    library(brms)
    library(rstan)
    #For execution on a local, multicore CPU with excess RAM we recommend calling
    options(mc.cores = parallel::detectCores())
    #To avoid recompilation of unchanged Stan programs, we recommend calling
    rstan_options(auto_write = TRUE)
    
      ##
    ##
    ## build and return a df of likelihood (the probability that the
    ## spider population is influenced by the oakMargin) by cluster by week
    ## UPDATE ELEMENT 5 of the inbound list and RETURN the entire list
    ##
    ##

  if (TRUE) {   # go through the tedious process of creating the brm models
                 # otherwise, get it from disk 

  
    ## total.df ( = df) , generated by evaluateDailySpiderCounts()
    ##                    'am' plus 'pm' data per 'timeList <- c('am', 'pm')'
    ##
    ## multiple records per week with columns
    ## week, transect, time, cluster, totalSpiders
    ##
  
  
    # estimate different mean populations across 3 groups of weeks reflecting the 
    # seasonal population decline
    # 
    # week 23, 24, 25           : mean 75, sd 15
    # week 26, 27, 28, 29, 30   : mean 50, sd 8
    # week 31, 32, 33, 34       : mean 15, sd 2
    
    # generate nrow(ave.df) random population numbers with a normal distribution
    # t.df$population <- rnorm(nrow(t.df), mean=50, sd=5)
    
    set.seed(10.2) # make the results reproducible
    
    # version 1 : df$population <- ifelse( (df$week>22 & df$week<26), rnorm(nrow(df), mean=75, sd=15),
    # version 1 :                          ifelse( (df$week>25 & df$week<31), rnorm(nrow(df), mean=25, sd=8),
    # version 1 :                                  rnorm(nrow(df), mean=15, sd=2)) )
    
    for (i in 1:9) {

        fileName <- paste("./code/output/clBRMsummary-", daytime, "-", i, ".txt", sep="")

        if (file.exists(fileName)) file.remove(fileName)

      }

  
    cl.st.list <- list()  # for each cluster  
    # build list of dataframes represting the seasonal population 
    # plus a variable log-population
    #
    label.list <- list()  # remember which cluster and seasonal timeframe
    #
    log.pop.list <- list()
    #
    #        rnorm() mean      cluster spider population         log population
    #   
    #             75                    794                            2.9       
    #             25                    264                            2.4
    #             15                    159                            2.2
    #
    # this is a list of 9
    # 34 observations of 8 variables
    # week, transect, time, cluster, totalSpiders, population, log_pop, contact_high
    #
    cl.st.list[[1]] <- df %>% dplyr::filter(week < 26 & cluster == 'one')
    cl.st.list[[1]]$population <- rnorm(nrow(cl.st.list[[1]]), mean=75, sd=15)
    cl.st.list[[1]]$population <- as.integer(cl.st.list[[1]]$population)
    cl.st.list[[1]]$log_pop <- log(cl.st.list[[1]]$population)  # R code 10.40
    cl.st.list[[1]]$contact_high <- ifelse( cl.st.list[[1]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[1]] <- 2.9
    label.list[[1]] <- "cluster: one, seasonal timeframe: one"
  
    cl.st.list[[2]] <- df %>% dplyr::filter(week > 25 & week < 32 & cluster == 'one')
    cl.st.list[[2]]$population <-rnorm(nrow(cl.st.list[[2]]), mean=25, sd=8)
    cl.st.list[[2]]$population <- as.integer(cl.st.list[[2]]$population)
    cl.st.list[[2]]$log_pop <- log(cl.st.list[[2]]$population)  # R code 10.40
    cl.st.list[[2]]$contact_high <- ifelse( cl.st.list[[2]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[2]] <- 2.4
    label.list[[2]] <- "cluster: one, seasonal timeframe: two"
    
    cl.st.list[[3]] <- df %>% dplyr::filter(week > 31 & cluster == 'one')
    cl.st.list[[3]]$population <-rnorm(nrow(cl.st.list[[3]]), mean=15, sd=2)
    cl.st.list[[3]]$population <- as.integer(cl.st.list[[3]]$population)
    cl.st.list[[3]]$log_pop <- log(cl.st.list[[3]]$population)  # R code 10.40
    cl.st.list[[3]]$contact_high <- ifelse( cl.st.list[[3]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[3]] <- 2.2
    label.list[[3]] <- "cluster: one, seasonal timeframe: three"
    
    cl.st.list[[4]] <- df %>% dplyr::filter(week < 26 & cluster == 'two')
    cl.st.list[[4]]$population <- rnorm(nrow(cl.st.list[[4]]), mean=75, sd=15)
    cl.st.list[[4]]$population <- as.integer(cl.st.list[[4]]$population)
    cl.st.list[[4]]$log_pop <- log(cl.st.list[[4]]$population)  # R code 10.40
    cl.st.list[[4]]$contact_high <- ifelse( cl.st.list[[4]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[4]] <- 2.9
    label.list[[4]] <- "cluster: two, seasonal timeframe: one"
    
    cl.st.list[[5]] <- df %>% dplyr::filter(week > 25 & week < 32 & cluster == 'two')
    cl.st.list[[5]]$population <-rnorm(nrow(cl.st.list[[5]]), mean=25, sd=8)
    cl.st.list[[5]]$population <- as.integer(cl.st.list[[5]]$population)
    cl.st.list[[5]]$log_pop <- log(cl.st.list[[5]]$population)  # R code 10.40
    cl.st.list[[5]]$contact_high <- ifelse( cl.st.list[[5]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[5]] <- 2.4
    label.list[[5]] <- "cluster: two, seasonal timeframe: two"
  
    cl.st.list[[6]] <- df %>% dplyr::filter(week > 31 & cluster == 'two')
    cl.st.list[[6]]$population <-rnorm(nrow(cl.st.list[[6]]), mean=15, sd=2)
    cl.st.list[[6]]$population <- as.integer(cl.st.list[[6]]$population)
    cl.st.list[[6]]$log_pop <- log(cl.st.list[[6]]$population)  # R code 10.40
    cl.st.list[[6]]$contact_high <- ifelse( cl.st.list[[6]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[6]] <- 2.2
    label.list[[6]] <- "cluster: two, seasonal timeframe: three"
    
    cl.st.list[[7]] <- df %>% dplyr::filter(week < 26 & cluster == 'three')
    cl.st.list[[7]]$population <- rnorm(nrow(cl.st.list[[7]]), mean=75, sd=15)
    cl.st.list[[7]]$population <- as.integer(cl.st.list[[7]]$population)
    cl.st.list[[7]]$log_pop <- log(cl.st.list[[7]]$population)  # R code 10.40
    cl.st.list[[7]]$contact_high <- ifelse( cl.st.list[[7]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[7]] <- 2.9
    label.list[[7]] <- "cluster: three, seasonal timeframe: one"
    
    cl.st.list[[8]] <- df %>% dplyr::filter(week > 25 & week < 32 & cluster == 'three')
    cl.st.list[[8]]$population <-rnorm(nrow(cl.st.list[[8]]), mean=25, sd=8)
    cl.st.list[[8]]$population <- as.integer(cl.st.list[[8]]$population)
    cl.st.list[[8]]$log_pop <- log(cl.st.list[[8]]$population)  # R code 10.40
    cl.st.list[[8]]$contact_high <- ifelse( cl.st.list[[8]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[8]] <- 2.4
    label.list[[8]] <- "cluster: three, seasonal timeframe: two"
    
    cl.st.list[[9]] <- df %>% dplyr::filter(week > 31 & cluster == 'three')
    cl.st.list[[9]]$population <-rnorm(nrow(cl.st.list[[9]]), mean=15, sd=2)
    cl.st.list[[9]]$population <- as.integer(cl.st.list[[9]]$population)
    cl.st.list[[9]]$log_pop <- log(cl.st.list[[9]]$population)  # R code 10.40
    cl.st.list[[9]]$contact_high <- ifelse( cl.st.list[[9]]$transect=="oakMargin" , 1 , 0 )
    log.pop.list[[9]] <- 2.2
    label.list[[9]] <- "cluster: three, seasonal timeframe: three"
  
  # plotWeekly(total.df)
  
    #########
    ## the model
    #########
    
    # the number of trapped spiders increases with log(population)
    
    # the number of trapped spiders increases with natural habitat support
    
    # the impact of population on trapped spiders increases with natural habital support
    
    
    
    likelihood.df <- NULL
    modelInput <-list()
    modelOutput <- list()
    postOutput <- list()
    
    for (i in 1:length(cl.st.list)) {  # build model for each seasonal timeframe
    
    
      if (TRUE) {
        
        b10.10 <-
          brm(data = cl.st.list[[i]], family = poisson,
              totalSpiders ~ 1 + log_pop + contact_high + contact_high:log_pop,  # yes, + contact_high:log_pop
              prior = c(prior(normal(0, 100), class = Intercept),
                        prior(normal(0, 1), class = b)),
             iter = 3000, warmup = 2000, chains = 4, cores = 4)
             # warmup increased to 2000 *assuming* "convergence issues" per setion 4.3 of
              # https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/linear-models.html
        

        modelInput[[i]] <- cl.st.list[[i]]
        modelOutput[[i]] <- b10.10
      

        # consider 2 clusters, each with a spider population of log(2.9)=794, calculate lambda, the expected 
        # trapped spiders, for each. 
        #
        # 794 spiders at 16 plants = 50 spiders per plant.
        #
        # draw samples from the posterior, plug them into the model, then invert the link function to
        # get back to the scale of the outcome variable. 
        #
        # how likely does the oakMargin 
        # McElreath code 10.43

        post <-
          posterior_samples(modelOutput[[i]])  # 
        
        post <-
          post %>%   
          mutate(lambda_high = exp(b_Intercept + b_contact_high + (b_log_pop + `b_log_pop:contact_high`) * log.pop.list[[i]]),
                 lambda_low  = exp(b_Intercept + b_log_pop * log.pop.list[[i]])) %>% 
          mutate(diff        = lambda_high - lambda_low) 
        
        like.df <- post %>%
          summarise(sum = sum(diff > 0)/length(diff))
        
      }  # end of TRUE/FALSE



        fileName <- paste("./code/output/clBRMsummary-", daytime, "-", i, ".txt", sep="")

        sink(file=fileName, append = TRUE, type = "output")
        print(writeLines(paste("\ngenerateLikelihoodV2()               ", Sys.time(), "\n\n", sep="")))
        print(writeLines(paste("i = ", i, "\n\n", sep="")))
        
        print(summary(modelOutput[[i]], prob=.89))

        sink(NULL)
      


    
      # figure out which cluster we are referring to
      if (i < 4) {
        cluster <- "one" 
      } else if (i > 6) {
        cluster <- "three"
      } else {
        cluster <- "two"
      }
    
      # figure out which seasonal timeframe we are referring to
      if (i == 1 | i == 4 | i == 7) {
        seasonalTimeframe <- "one" 
      } else if (i == 2 | i == 5 | i == 8) {
        seasonalTimeframe <- "two"
      } else {
        seasonalTimeframe <- "three"
      }      
    
      temp2.df <- data.frame(cluster, seasonalTimeframe, like.df$sum) 
      # column names need to match for rbind() to work
      names(temp2.df) <- c("cluster", "seasonalTimeframe", "plausibility")
    
      # tack it on
      if (!exists('likelihood.df')) {
        likelihood.df <- temp2.df
        # (so, on the first pass the column names are cool)
      } else {
        likelihood.df <- rbind(likelihood.df, temp2.df)
      }
    
    }  # end of for(){}
    

    saveRDS(likelihood.df, paste("./code/output/likelihood-", daytime, ".rds", sep=""))

  } else {   # read the structure from disk

    likelihood.df <- readRDS(paste("./code/output/likelihood-", daytime, ".rds", sep=""))

  }

  
  gg <- plotLikelihood(df=likelihood.df, sub=paste("daytime: ", daytime, sep=""), cap="model 794:264:159 spider population seasonal trend")

  # cleanup
  rm(list)
  detach("package:brms", unload=TRUE) 
  detach("package:rstan", unload=TRUE) 
  #
  
  return(gg)
  
}
